# Generated by Django 3.2.9 on 2021-11-27 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='master',
            name='branch_master',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='salon.branch'),
            preserve_default=False,
        ),
    ]
