# Generated by Django 3.2.9 on 2021-11-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_auto_20211127_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
