# Generated by Django 3.2.9 on 2021-11-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_branch_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='image',
            field=models.ImageField(default='', upload_to='masters'),
            preserve_default=False,
        ),
    ]
